name: Copilot Setup Steps

steps:
  - name: Set up Node.js 22
    uses: actions/setup-node@89d709d423dc495668cd762a18dd4a070611be3f
    with:
      node-version: "22"
      cache: "npm"

  - name: Install dependencies
    run: npm ci