name: Copilot Setup Steps

# Minimal setup steps for GitHub Copilot to work with this repository
steps:
  - name: Set up Node.js 22
    uses: actions/setup-node@89d709d423dc495668cd762a18dd4a070611be3f
    with:
      node-version: "22"

  - name: Install dependencies
    run: npm ci