version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "09:00"
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 5
    groups:
      patch-and-minor-updates:
        update-types:
          - "patch"
          - "minor"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
    commit-message:
      prefix: "deps"
    open-pull-requests-limit: 10
    groups:
      patch-and-minor-updates:
        applies-to: version-updates
        update-types:
          - "patch"
          - "minor"
      storybook:
        applies-to: version-updates
        patterns:
          - "@storybook/*"
          - "storybook"
      eslint:
        applies-to: version-updates
        patterns:
          - "eslint"
          - "eslint-*"
      vitest:
        applies-to: version-updates
        patterns:
          - "vitest"
          - "@vitest/*"
      commitlint:
        applies-to: version-updates
        patterns:
          - "@commitlint/*"
