#!/bin/sh
#
# This hook checks if one of the commit messages in current branch contains a prefix of "fix" or "feat"
# If not, it will print a warning message suggesting to include one before merging the PR
# for automatic semantic versioning release.
# for more info on commit message format, see https://www.conventionalcommits.org/en/v1.0.0/

RED='\033[0;31m'
NC='\033[0m'

CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)

MSG_HISTORY=$(git cherry -v main | cut -d ' ' -f 3-)

PATTERN="^fix|feat(\(.*\))?\!?:"

if [ -z "$(grep -E -i "$PATTERN" "$1")" ]; then
	for i in $MSG_HISTORY; do
		if [ -n "$(echo "$i" | grep -E -i "$PATTERN")" ]; then
			exit 0
		fi
	done
	echo "${RED}Missing commit message with prefix feat/fix. Consider adding one before merging PR for automatic semver release.${NC}"
fi

exit 0