name: Release

on:
  release:
    types: ["published"]

concurrency:
  group: nwc
  cancel-in-progress: false

jobs:
  npm-publish:
    runs-on:
      group: Personalisation
      labels: [self-hosted, linux, x64]
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref || github.ref_name }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Set registry
        run: npm set registry https://npm.nos.to

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Publish to NPM
        run: npm publish --registry https://npm.nos.to/ || true
